language: generic                                               # Add this line to avoid errors like - “rakefile not found” 

sudo: required
services:
  - docker

before_install:
  - docker build -t ravilkhalilov/react-test -f ./client/Dockerfile.dev  ./client

script: 
  - docker run -e CI=true ravilkhalilov/react-test npm test     # https://facebook.github.io/create-react-app/docs/running-tests#linux-macos-bash

after_success: 
  - docker build -t ravilkhalilov/multi-client ./client         # It will use by default Dockerfile to create image. Docker by default is looking for Dockerfile, not Dockerfile.dev
  - docker build -t ravilkhalilov/multi-nginx ./nginx           # It will use by default Dockerfile to create image. Docker by default is looking for Dockerfile, not Dockerfile.dev 
  - docker build -t ravilkhalilov/multi-server ./server         # It will use by default Dockerfile to create image. Docker by default is looking for Dockerfile, not Dockerfile.dev 
  - docker build -t ravilkhalilov/multi-worker ./worker         # It will use by default Dockerfile to create image. Docker by default is looking for Dockerfile, not Dockerfile.dev

# Login to Docker Hub with our credentials specified in repository setting in TravisCI
# TravisCI will read both variables specified for this repository
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin

# Take those images and push them to docker hub
  - docker push ravilkhalilov/multi-client
  - docker push ravilkhalilov/multi-nginx
  - docker push ravilkhalilov/multi-server
  - docker push ravilkhalilov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-289483554334'
  bucket_path: 'multi-docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY